### ISSUE TITLE
Issue: Unable to use "Cmd+." as a Custom Shortcut Key on Macos

### ISSUE THREAD

**Issue by MSAdministrator** [klaussinani/ao#11]
## Description

I am running High Sierra on Mac and for some reason I cannot access the Settings menu in AO.  I have changed the darwin.json configuration to another option but it still will not pop up by using either the menu directly or via keyboard shortcut.

### Error Message (if any)

No error message found, just doesn't react/open.

## Relevant Links (if any)

NA

## Environment

Tell us which operating system you are using, as well as which version of [Ao](https://github.com/klauscfhq/ao/releases/latest).
Run the following script to get your OS info quickly.

```bash
OS Type: 	Darwin
OS Platform:	darwin
OS Release: 	17.4.0
Architecture: 	x64
```

## Additional Information

NA

**Comment by klauscfhq** [comment]
Would you mind sharing the contents of your `~/.ao.json` file?

**Comment by klauscfhq** [comment]
Unfortunately the `Cmd+.` shortcut key is reserved for the `Edit Shortcut Keys` option, which is hardcoded and not available for modification in the `~/.ao.json` file, thus it conflicts with your custom `"settings": "Cmd+."` option. The next release will address this issue by making the `Edit Shortcut Keys` option editable, in order to prevent any similar future issues. For the time being you can try using a different shortcut key to toggle your `Settings`, the default `"Cmd+."` could be an option. Other than that everything seems perfect, thank you for taking the time to report it : )

**Comment by MSAdministrator** [comment]
@klauscfhq Well, now I am having another issue - not sure what is going on.  I removed my `~/.ao.json` and now it won't load.  The application loads, but not the web app.  I also removed the application and re-installed and still the same issue.  I'll keep messing with this, unless you know of way to remove the application completely?

Thanks,

**Comment by MSAdministrator** [comment]
Also, I just downloaded 5.2.0 and installed it as well - still having the same issue.  Something is sticking around for some reason.

**Comment by klauscfhq** [comment]
You can try uninstalling and then deleting the `~/Library/Application Support/Ao` directory. After that clean installing from scratch should bring everything back to normal : )

**Comment by MSAdministrator** [comment]
@klauscfhq Thanks for the help again!  I did that and re-installed but I am still unable to access the settings in the menu either by shortcut or via the menu.  Here is an example (side note, I also did this with 5.2.0 and it is not working on there as well):
![2018-02-20 19 50 39](https://user-images.githubusercontent.com/10687261/36457422-f0071512-1677-11e8-97b6-a756c4d2f7fb.gif)

**Comment by MSAdministrator** [comment]
@klauscfhq Here's a better one I think:
![2018-02-20 20 11 51](https://user-images.githubusercontent.com/10687261/36457966-93d24476-167a-11e8-9b02-c2dd61a1771b.gif)

**Comment by klauscfhq** [comment]
Yep, now it makes sense. It looks like that Ao is loading a different version of the Microsoft Todo interface, probably an updated or latest one. That is the reason for not toggling the Settings menu, as well as the console errors, since the in-use by Ao `class names` are not present there. The `Cmd+,` shortcut actually toggles the native `Settings` menu of the original/traditional Microsoft Todo interface. Here is a quick look of it on Windows, same goes for Linux;
 
![2018-02-21_03-14-56](https://user-images.githubusercontent.com/12670537/36458233-7b638f94-16b6-11e8-8786-db56f98f7cb3.gif)

It could be that the Microsoft Todo app is under a gradual updating process and your account belongs to a circle of users that were given access to it first or it could just be a a Macos thing, but I tend to think more of the first one as the cause. I will have a better look into it and come up with a way to address it. Thank you a lot for bringing it up 👍

For the record, you can probably still access the settings menu by click the cogwheel icon at the top bar.

**Comment by MSAdministrator** [comment]
@klauscfhq Thanks for the explanation!  Just wanted you to be aware.

Also, I'm going to suggest another item in a #12

**Comment by klaussinani** [comment]
New 6.0.0 release, supporting the updated Microsoft To-Do interface, is now out. Full changelog & binaries are available on the [GitHub Releases page](https://github.com/klaussinani/ao/releases/tag/v6.0.0).
