### ISSUE TITLE
Unable to build ao

### ISSUE THREAD

**Issue by Modelmat** [klaussinani/ao#55]
Since https://github.com/klaussinani/ao/commit/944ab7a9b160f7afe4bf4fcc9a37e993722dcb1d, `npm run dist` no longer exists.

When trying to build this package, the only option is `npm run release`, which builds all the packages. It is no longer possible to just do `npm run dist` and create the dist/linux-unpacked folder.

This has broken the [ao-git](https://aur.archlinux.org/packages/ao-git/) AUR package.
Sidenote, the [ao](https://aur.archlinux.org/packages/ao/) AUR package is out of date.

**Comment by Modelmat** [comment]
I saw you noticed this, was this intentional?

**Comment by roachsinai** [comment]
So, any updates?

**Comment by Modelmat** [comment]
@klaussinani Could we please get a fix for this? It's been nearly two months.

**Comment by novdddd** [comment]
You can do it yourself u know, not hard, search a bit 😋

**Comment by klaussinani** [comment]
This side effect has been due to the modifications that were delivered through updates to [`electron-builder`](https://github.com/electron-userland/electron-builder) devDependency by the electron-builder maintainers/team. A viable solution would be to fork the Ao repository and try to tweak the building configuration of `electron-builder` through the `package.json` file. More info on the `electron-builder` module available on the official homepage: https://www.electron.build

**Comment by Modelmat** [comment]
Yup, I've figured it out. `npx electron-builder` allows me to run the build script.
I'm updating the `ao-git` AUR package now.
